# Generated by Django 5.2.16 on 2026-07-21 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('visit_date', models.DateField()),
                ('file', models.FileField(upload_to='external_tickets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_tickets',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
