# Generated by Django 5.2.16 on 2026-07-19 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class for the category', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['district_name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('State', 'State'), ('Union Territory', 'Union Territory')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'db_table': 'states',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.district')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['city_name'],
                'unique_together': {('district', 'city_name')},
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(blank=True, max_length=150, null=True)),
                ('place_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('history', models.TextField(blank=True, null=True)),
                ('year_established', models.CharField(blank=True, max_length=100, null=True)),
                ('unesco_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('asi_protected', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('opening_days', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('entry_fee_indian', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('entry_fee_foreigner', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('student_discount', models.CharField(blank=True, max_length=100, null=True)),
                ('senior_citizen_discount', models.CharField(blank=True, max_length=100, null=True)),
                ('parking_available', models.CharField(blank=True, max_length=20, null=True)),
                ('wheelchair_accessible', models.CharField(blank=True, max_length=50, null=True)),
                ('guided_tours', models.CharField(blank=True, max_length=50, null=True)),
                ('audio_guide', models.CharField(blank=True, max_length=100, null=True)),
                ('photography_allowed', models.CharField(blank=True, max_length=20, null=True)),
                ('videography_allowed', models.CharField(blank=True, max_length=100, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('average_visit_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('nearest_airport', models.CharField(blank=True, max_length=150, null=True)),
                ('nearest_railway_station', models.CharField(blank=True, max_length=150, null=True)),
                ('nearest_bus_station', models.CharField(blank=True, max_length=150, null=True)),
                ('official_website', models.URLField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('number_of_reviews', models.IntegerField(default=0)),
                ('main_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Renovation', 'Under Renovation')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='places', to='core.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='core.city')),
            ],
            options={
                'db_table': 'places',
                'ordering': ['-rating', '-number_of_reviews'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.place')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('sort_order', models.IntegerField(default=0)),
                ('image_type', models.CharField(choices=[('Gallery', 'Gallery'), ('Cover', 'Cover'), ('Panorama', 'Panorama')], default='Gallery', max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.place')),
            ],
            options={
                'db_table': 'place_images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.state'),
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_prices', to='core.place')),
            ],
            options={
                'db_table': 'ticket_prices',
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category'], name='idx_places_category'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city'], name='idx_places_city'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['unesco_status'], name='idx_places_unesco'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['rating'], name='idx_places_rating'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'district_name')},
        ),
    ]
