# Generated by Django 5.2.16 on 2026-07-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='booking_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
